# 2DGN1
Center_2DGF_N1_T1_4_1<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/1-1-1.geojson")
Center_2DGF_N1_T1_4_2<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/1-1-2.geojson")
Center_2DGF_N1_T1_4_3<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/1-1-3.geojson")
Center_2DGF_N1_T1_4_4<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/1-1-4.geojson")
Center_2DGF_N1_T1_4_5<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/1-1-5.geojson")
Center_2DGF_N1_T1_4_6<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/1-1-6.geojson")
Center_2DGF_N1_T1_4_7<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/1-1-7.geojson")
Center_2DGF_N1_T1_4_8<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/1-1-8.geojson")
Center_2DGF_N1_T1_4_9<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/1-1-9.geojson")

Center_2DGF_N1_T5_7_1<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/1-2-1.geojson")
Center_2DGF_N1_T5_7_2<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/1-2-2.geojson")
Center_2DGF_N1_T5_7_3<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/1-2-3.geojson")
Center_2DGF_N1_T5_7_4<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/1-2-4.geojson")
Center_2DGF_N1_T5_7_5<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/1-2-5.geojson")
Center_2DGF_N1_T5_7_6<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/1-2-6.geojson")
Center_2DGF_N1_T5_7_7<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/1-2-7.geojson")
Center_2DGF_N1_T5_7_8<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/1-2-8.geojson")
Center_2DGF_N1_T5_7_9<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/1-2-9.geojson")


Center_2DGF_N1_T8_10_1<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/1-3-1.geojson")
Center_2DGF_N1_T8_10_2<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/1-3-2.geojson")
Center_2DGF_N1_T8_10_3<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/1-3-3.geojson")
Center_2DGF_N1_T8_10_4<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/1-3-4.geojson")
Center_2DGF_N1_T8_10_5<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/1-3-5.geojson")
Center_2DGF_N1_T8_10_6<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/1-3-6.geojson")
Center_2DGF_N1_T8_10_7<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/1-3-7.geojson")
Center_2DGF_N1_T8_10_8<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/1-3-8.geojson")

Center_2DGF_N1_T11_13_1<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/1-4-1.geojson")
Center_2DGF_N1_T11_13_2<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/1-4-2.geojson")
Center_2DGF_N1_T11_13_3<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/1-4-3.geojson")
Center_2DGF_N1_T11_13_4<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/1-4-4.geojson")
Center_2DGF_N1_T11_13_5<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/1-4-5.geojson")
Center_2DGF_N1_T11_13_6<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/1-4-6.geojson")
Center_2DGF_N1_T11_13_7<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/1-4-7.geojson")
Center_2DGF_N1_T11_13_8<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/1-4-8.geojson")
Center_2DGF_N1_T11_13_9<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/1-4-9.geojson")

Center_2DGF_N1_L1_3_1<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/1-5-1.geojson")
Center_2DGF_N1_L1_3_2<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/1-5-2.geojson")
Center_2DGF_N1_L1_3_3<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/1-5-3.geojson")
Center_2DGF_N1_L1_3_4<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/1-5-4.geojson")
Center_2DGF_N1_L1_3_5<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/1-5-5.geojson")
Center_2DGF_N1_L1_3_6<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/1-5-6.geojson")
Center_2DGF_N1_L1_3_7<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/1-5-7.geojson")
Center_2DGF_N1_L1_3_8<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/1-5-8.geojson")
Center_2DGF_N1_L1_3_9<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/1-5-9.geojson")
Center_2DGF_N1_L1_3_10<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/1-5-10.geojson")


Center_2DGF_N1_L45_1<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/1-6-1.geojson")
Center_2DGF_N1_L45_2<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/1-6-2.geojson")
Center_2DGF_N1_L45_3<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/1-6-3.geojson")
Center_2DGF_N1_L45_4<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/1-6-4.geojson")
Center_2DGF_N1_L45_5<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/1-6-5.geojson")
Center_2DGF_N1_L45_6<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/1-6-6.geojson")


Center_2DGF_N1_L6S1_1<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/1-7-1.geojson")
Center_2DGF_N1_L6S1_2<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/1-7-2.geojson")
Center_2DGF_N1_L6S1_3<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/1-7-3.geojson")
Center_2DGF_N1_L6S1_4<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/1-7-4.geojson")
Center_2DGF_N1_L6S1_5<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/1-7-5.geojson")
Center_2DGF_N1_L6S1_6<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/1-7-6.geojson")
Center_2DGF_N1_L6S1_7<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/1-7-7.geojson")
Center_2DGF_N1_L6S1_8<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/1-7-8.geojson")

Center_2DGF_N1_S2_4_1<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/1-8-1.geojson")
Center_2DGF_N1_S2_4_2<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/1-8-2.geojson")
Center_2DGF_N1_S2_4_3<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/1-8-3.geojson")
Center_2DGF_N1_S2_4_4<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/1-8-4.geojson")
Center_2DGF_N1_S2_4_5<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/1-8-5.geojson")
Center_2DGF_N1_S2_4_6<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/1-8-6.geojson")
Center_2DGF_N1_S2_4_7<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/1-8-7.geojson")
Center_2DGF_N1_S2_4_8<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/1-8-8.geojson")



# 2DGFN2
Center_2DGF_N2_T1_4_1<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/2-1-1.geojson")
Center_2DGF_N2_T1_4_2<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/2-1-2.geojson")
Center_2DGF_N2_T1_4_3<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/2-1-3.geojson")
Center_2DGF_N2_T1_4_4<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/2-1-4.geojson")
Center_2DGF_N2_T1_4_5<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/2-1-5.geojson")
Center_2DGF_N2_T1_4_6<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/2-1-6.geojson")
Center_2DGF_N2_T1_4_7<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/2-1-7.geojson")
Center_2DGF_N2_T1_4_8<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/2-1-8.geojson")
Center_2DGF_N2_T1_4_9<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/2-1-9.geojson")
Center_2DGF_N2_T1_4_10<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/2-1-10.geojson")


Center_2DGF_N2_T5_7_1<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/2-2-1.geojson")
Center_2DGF_N2_T5_7_2<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/2-2-2.geojson")
Center_2DGF_N2_T5_7_3<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/2-2-3.geojson")
Center_2DGF_N2_T5_7_4<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/2-2-4.geojson")
Center_2DGF_N2_T5_7_5<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/2-2-5.geojson")
Center_2DGF_N2_T5_7_6<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/2-2-6.geojson")
Center_2DGF_N2_T5_7_7<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/2-2-7.geojson")
Center_2DGF_N2_T5_7_8<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/2-2-8.geojson")


Center_2DGF_N2_T8_10_1<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/2-3-1.geojson")
Center_2DGF_N2_T8_10_2<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/2-3-2.geojson")
Center_2DGF_N2_T8_10_3<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/2-3-3.geojson")
Center_2DGF_N2_T8_10_4<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/2-3-4.geojson")
Center_2DGF_N2_T8_10_5<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/2-3-5.geojson")
Center_2DGF_N2_T8_10_6<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/2-3-6.geojson")
Center_2DGF_N2_T8_10_7<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/2-3-7.geojson")

Center_2DGF_N2_T11_13_1<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/2-4-1.geojson")
Center_2DGF_N2_T11_13_2<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/2-4-2.geojson")
Center_2DGF_N2_T11_13_3<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/2-4-3.geojson")
Center_2DGF_N2_T11_13_4<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/2-4-4.geojson")
Center_2DGF_N2_T11_13_5<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/2-4-5.geojson")
Center_2DGF_N2_T11_13_6<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/2-4-6.geojson")
Center_2DGF_N2_T11_13_7<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/2-4-7.geojson")
Center_2DGF_N2_T11_13_8<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/2-4-8.geojson")

Center_2DGF_N2_L1_3_1<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/2-5-1.geojson")
Center_2DGF_N2_L1_3_2<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/2-5-2.geojson")
Center_2DGF_N2_L1_3_3<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/2-5-3.geojson")
Center_2DGF_N2_L1_3_4<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/2-5-4.geojson")
Center_2DGF_N2_L1_3_5<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/2-5-5.geojson")
Center_2DGF_N2_L1_3_6<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/2-5-6.geojson")
Center_2DGF_N2_L1_3_7<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/2-5-7.geojson")
Center_2DGF_N2_L1_3_8<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/2-5-8.geojson")
Center_2DGF_N2_L1_3_9<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/2-5-9.geojson")

Center_2DGF_N2_L45_1<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/2-6-1.geojson")
Center_2DGF_N2_L45_2<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/2-6-2.geojson")
Center_2DGF_N2_L45_3<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/2-6-3.geojson")
Center_2DGF_N2_L45_4<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/2-6-4.geojson")
Center_2DGF_N2_L45_5<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/2-6-5.geojson")
Center_2DGF_N2_L45_6<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/2-6-6.geojson")

Center_2DGF_N2_L6S1_1<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/2-7-1.geojson")
Center_2DGF_N2_L6S1_2<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/2-7-2.geojson")
Center_2DGF_N2_L6S1_3<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/2-7-3.geojson")
Center_2DGF_N2_L6S1_4<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/2-7-4.geojson")
Center_2DGF_N2_L6S1_5<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/2-7-5.geojson")
Center_2DGF_N2_L6S1_6<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/2-7-6.geojson")
Center_2DGF_N2_L6S1_7<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/2-7-7.geojson")
Center_2DGF_N2_L6S1_8<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/2-7-8.geojson")

Center_2DGF_N2_S2_4_1<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/2-8-1.geojson")
Center_2DGF_N2_S2_4_2<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/2-8-2.geojson")
Center_2DGF_N2_S2_4_3<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/2-8-3.geojson")
Center_2DGF_N2_S2_4_4<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/2-8-4.geojson")
Center_2DGF_N2_S2_4_5<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/2-8-5.geojson")
Center_2DGF_N2_S2_4_6<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/2-8-6.geojson")
Center_2DGF_N2_S2_4_7<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/2-8-7.geojson")
Center_2DGF_N2_S2_4_8<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/2-8-8.geojson")
Center_2DGF_N2_S2_4_9<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/2-8-9.geojson")


# 2DGFN3
Center_2DGF_N3_T1_4_1<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/3-1-1.geojson")
Center_2DGF_N3_T1_4_2<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/3-1-2.geojson")
Center_2DGF_N3_T1_4_3<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/3-1-3.geojson")
Center_2DGF_N3_T1_4_4<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/3-1-4.geojson")
Center_2DGF_N3_T1_4_5<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/3-1-5.geojson")
Center_2DGF_N3_T1_4_6<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/3-1-6.geojson")
Center_2DGF_N3_T1_4_7<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/3-1-7.geojson")
Center_2DGF_N3_T1_4_8<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/3-1-8.geojson")


Center_2DGF_N3_T5_7_1<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/3-2-1.geojson")
Center_2DGF_N3_T5_7_2<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/3-2-2.geojson")
Center_2DGF_N3_T5_7_3<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/3-2-3.geojson")
Center_2DGF_N3_T5_7_4<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/3-2-4.geojson")
Center_2DGF_N3_T5_7_5<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/3-2-5.geojson")
Center_2DGF_N3_T5_7_6<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/3-2-6.geojson")
Center_2DGF_N3_T5_7_7<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/3-2-7.geojson")
Center_2DGF_N3_T5_7_8<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/3-2-8.geojson")
Center_2DGF_N3_T5_7_9<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/3-2-9.geojson")

Center_2DGF_N3_T8_10_1<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/3-3-1.geojson")
Center_2DGF_N3_T8_10_2<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/3-3-2.geojson")
Center_2DGF_N3_T8_10_3<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/3-3-3.geojson")
Center_2DGF_N3_T8_10_4<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/3-3-4.geojson")
Center_2DGF_N3_T8_10_5<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/3-3-5.geojson")
Center_2DGF_N3_T8_10_6<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/3-3-6.geojson")
Center_2DGF_N3_T8_10_7<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/3-3-7.geojson")
Center_2DGF_N3_T8_10_8<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/3-3-8.geojson")
Center_2DGF_N3_T8_10_9<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/3-3-9.geojson")

Center_2DGF_N3_T11_13_1<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/3-4-1.geojson")
Center_2DGF_N3_T11_13_2<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/3-4-2.geojson")
Center_2DGF_N3_T11_13_3<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/3-4-3.geojson")
Center_2DGF_N3_T11_13_4<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/3-4-4.geojson")
Center_2DGF_N3_T11_13_5<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/3-4-5.geojson")
Center_2DGF_N3_T11_13_6<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/3-4-6.geojson")
Center_2DGF_N3_T11_13_7<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/3-4-7.geojson")
Center_2DGF_N3_T11_13_8<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/3-4-8.geojson")

Center_2DGF_N3_L1_3_1<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/3-5-1.geojson")
Center_2DGF_N3_L1_3_2<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/3-5-2.geojson")
Center_2DGF_N3_L1_3_3<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/3-5-3.geojson")
Center_2DGF_N3_L1_3_4<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/3-5-4.geojson")
Center_2DGF_N3_L1_3_5<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/3-5-5.geojson")
Center_2DGF_N3_L1_3_6<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/3-5-6.geojson")
Center_2DGF_N3_L1_3_7<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/3-5-7.geojson")
Center_2DGF_N3_L1_3_8<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/3-5-8.geojson")

Center_2DGF_N3_L45_1<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/3-6-1.geojson")
Center_2DGF_N3_L45_2<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/3-6-2.geojson")
Center_2DGF_N3_L45_3<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/3-6-3.geojson")
Center_2DGF_N3_L45_4<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/3-6-4.geojson")
Center_2DGF_N3_L45_5<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/3-6-5.geojson")
Center_2DGF_N3_L45_6<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/3-6-6.geojson")

Center_2DGF_N3_L6S1_1<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/3-7-1.geojson")
Center_2DGF_N3_L6S1_2<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/3-7-2.geojson")
Center_2DGF_N3_L6S1_3<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/3-7-3.geojson")
Center_2DGF_N3_L6S1_4<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/3-7-4.geojson")
Center_2DGF_N3_L6S1_5<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/3-7-5.geojson")
Center_2DGF_N3_L6S1_6<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/3-7-6.geojson")
Center_2DGF_N3_L6S1_7<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/3-7-7.geojson")

Center_2DGF_N3_S2_4_1<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/3-8-1.geojson")
Center_2DGF_N3_S2_4_2<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/3-8-2.geojson")
Center_2DGF_N3_S2_4_3<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/3-8-3.geojson")
Center_2DGF_N3_S2_4_4<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/3-8-4.geojson")
Center_2DGF_N3_S2_4_5<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/3-8-5.geojson")
Center_2DGF_N3_S2_4_6<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/3-8-6.geojson")
Center_2DGF_N3_S2_4_7<- geojson_sf("./Xenium_SC/ROI_geojson/2DGF_center/3-8-7.geojson")


# 2DGMN1
Center_2DGM_N1_T1_4_1<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/1-1-1.geojson")
Center_2DGM_N1_T1_4_2<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/1-1-2.geojson")
Center_2DGM_N1_T1_4_3<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/1-1-3.geojson")
Center_2DGM_N1_T1_4_4<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/1-1-4.geojson")
Center_2DGM_N1_T1_4_5<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/1-1-5.geojson")
Center_2DGM_N1_T1_4_6<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/1-1-6.geojson")
Center_2DGM_N1_T1_4_7<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/1-1-7.geojson")
Center_2DGM_N1_T1_4_8<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/1-1-8.geojson")
Center_2DGM_N1_T1_4_9<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/1-1-9.geojson")
Center_2DGM_N1_T1_4_10<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/1-1-10.geojson")

Center_2DGM_N1_T5_7_1<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/1-2-1.geojson")
Center_2DGM_N1_T5_7_2<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/1-2-2.geojson")
Center_2DGM_N1_T5_7_3<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/1-2-3.geojson")
Center_2DGM_N1_T5_7_4<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/1-2-4.geojson")
Center_2DGM_N1_T5_7_5<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/1-2-5.geojson")
Center_2DGM_N1_T5_7_6<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/1-2-6.geojson")
Center_2DGM_N1_T5_7_7<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/1-2-7.geojson")
Center_2DGM_N1_T5_7_8<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/1-2-8.geojson")
Center_2DGM_N1_T5_7_9<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/1-2-9.geojson")


Center_2DGM_N1_T8_10_1<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/1-3-1.geojson")
Center_2DGM_N1_T8_10_2<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/1-3-2.geojson")
Center_2DGM_N1_T8_10_3<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/1-3-3.geojson")
Center_2DGM_N1_T8_10_4<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/1-3-4.geojson")
Center_2DGM_N1_T8_10_5<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/1-3-5.geojson")
Center_2DGM_N1_T8_10_6<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/1-3-6.geojson")
Center_2DGM_N1_T8_10_7<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/1-3-7.geojson")
Center_2DGM_N1_T8_10_8<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/1-3-8.geojson")
Center_2DGM_N1_T8_10_9<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/1-3-9.geojson")


Center_2DGM_N1_T11_13_1<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/1-4-1.geojson")
Center_2DGM_N1_T11_13_2<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/1-4-2.geojson")
Center_2DGM_N1_T11_13_3<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/1-4-3.geojson")
Center_2DGM_N1_T11_13_4<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/1-4-4.geojson")
Center_2DGM_N1_T11_13_5<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/1-4-5.geojson")
Center_2DGM_N1_T11_13_6<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/1-4-6.geojson")
Center_2DGM_N1_T11_13_7<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/1-4-7.geojson")
Center_2DGM_N1_T11_13_8<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/1-4-8.geojson")

Center_2DGM_N1_L1_3_1<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/1-5-1.geojson")
Center_2DGM_N1_L1_3_2<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/1-5-2.geojson")
Center_2DGM_N1_L1_3_3<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/1-5-3.geojson")
Center_2DGM_N1_L1_3_4<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/1-5-4.geojson")
Center_2DGM_N1_L1_3_5<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/1-5-5.geojson")
Center_2DGM_N1_L1_3_6<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/1-5-6.geojson")
Center_2DGM_N1_L1_3_7<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/1-5-7.geojson")
Center_2DGM_N1_L1_3_8<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/1-5-8.geojson")
Center_2DGM_N1_L1_3_9<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/1-5-9.geojson")
Center_2DGM_N1_L1_3_10<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/1-5-10.geojson")

Center_2DGM_N1_L45_1<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/1-6-1.geojson")
Center_2DGM_N1_L45_2<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/1-6-2.geojson")
Center_2DGM_N1_L45_3<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/1-6-3.geojson")
Center_2DGM_N1_L45_4<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/1-6-4.geojson")
Center_2DGM_N1_L45_5<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/1-6-5.geojson")
Center_2DGM_N1_L45_6<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/1-6-6.geojson")


Center_2DGM_N1_L6S1_1<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/1-7-1.geojson")
Center_2DGM_N1_L6S1_2<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/1-7-2.geojson")
Center_2DGM_N1_L6S1_3<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/1-7-3.geojson")
Center_2DGM_N1_L6S1_4<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/1-7-4.geojson")
Center_2DGM_N1_L6S1_5<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/1-7-5.geojson")
Center_2DGM_N1_L6S1_6<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/1-7-6.geojson")
Center_2DGM_N1_L6S1_7<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/1-7-7.geojson")

Center_2DGM_N1_S2_4_1<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/1-8-1.geojson")
Center_2DGM_N1_S2_4_2<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/1-8-2.geojson")
Center_2DGM_N1_S2_4_3<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/1-8-3.geojson")
Center_2DGM_N1_S2_4_4<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/1-8-4.geojson")
Center_2DGM_N1_S2_4_5<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/1-8-5.geojson")



# 2DGMN2
Center_2DGM_N2_T1_4_1<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/2-1-1.geojson")
Center_2DGM_N2_T1_4_2<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/2-1-2.geojson")
Center_2DGM_N2_T1_4_3<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/2-1-3.geojson")
Center_2DGM_N2_T1_4_4<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/2-1-4.geojson")
Center_2DGM_N2_T1_4_5<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/2-1-5.geojson")
Center_2DGM_N2_T1_4_6<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/2-1-6.geojson")
Center_2DGM_N2_T1_4_7<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/2-1-7.geojson")
Center_2DGM_N2_T1_4_8<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/2-1-8.geojson")
Center_2DGM_N2_T1_4_9<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/2-1-9.geojson")
Center_2DGM_N2_T1_4_10<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/2-1-10.geojson")

Center_2DGM_N2_T5_7_1<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/2-2-1.geojson")
Center_2DGM_N2_T5_7_2<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/2-2-2.geojson")
Center_2DGM_N2_T5_7_3<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/2-2-3.geojson")
Center_2DGM_N2_T5_7_4<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/2-2-4.geojson")
Center_2DGM_N2_T5_7_5<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/2-2-5.geojson")
Center_2DGM_N2_T5_7_6<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/2-2-6.geojson")
Center_2DGM_N2_T5_7_7<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/2-2-7.geojson")
Center_2DGM_N2_T5_7_8<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/2-2-8.geojson")

Center_2DGM_N2_T8_10_1<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/2-3-1.geojson")
Center_2DGM_N2_T8_10_2<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/2-3-2.geojson")
Center_2DGM_N2_T8_10_3<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/2-3-3.geojson")
Center_2DGM_N2_T8_10_4<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/2-3-4.geojson")
Center_2DGM_N2_T8_10_5<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/2-3-5.geojson")
Center_2DGM_N2_T8_10_6<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/2-3-6.geojson")
Center_2DGM_N2_T8_10_7<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/2-3-7.geojson")
Center_2DGM_N2_T8_10_8<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/2-3-8.geojson")

Center_2DGM_N2_T11_13_1<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/2-4-1.geojson")
Center_2DGM_N2_T11_13_2<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/2-4-2.geojson")
Center_2DGM_N2_T11_13_3<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/2-4-3.geojson")
Center_2DGM_N2_T11_13_4<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/2-4-4.geojson")
Center_2DGM_N2_T11_13_5<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/2-4-5.geojson")
Center_2DGM_N2_T11_13_6<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/2-4-6.geojson")
Center_2DGM_N2_T11_13_7<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/2-4-7.geojson")
Center_2DGM_N2_T11_13_8<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/2-4-8.geojson")
Center_2DGM_N2_T11_13_9<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/2-4-9.geojson")
Center_2DGM_N2_T11_13_10<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/2-4-10.geojson")

Center_2DGM_N2_L1_3_1<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/2-5-1.geojson")
Center_2DGM_N2_L1_3_2<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/2-5-2.geojson")
Center_2DGM_N2_L1_3_3<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/2-5-3.geojson")
Center_2DGM_N2_L1_3_4<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/2-5-4.geojson")
Center_2DGM_N2_L1_3_5<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/2-5-5.geojson")
Center_2DGM_N2_L1_3_6<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/2-5-6.geojson")
Center_2DGM_N2_L1_3_7<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/2-5-7.geojson")
Center_2DGM_N2_L1_3_8<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/2-5-8.geojson")
Center_2DGM_N2_L1_3_9<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/2-5-9.geojson")
Center_2DGM_N2_L1_3_10<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/2-5-10.geojson")


Center_2DGM_N2_L45_1<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/2-6-1.geojson")
Center_2DGM_N2_L45_2<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/2-6-2.geojson")
Center_2DGM_N2_L45_3<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/2-6-3.geojson")
Center_2DGM_N2_L45_4<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/2-6-4.geojson")
Center_2DGM_N2_L45_5<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/2-6-5.geojson")

Center_2DGM_N2_L6S1_1<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/2-7-1.geojson")
Center_2DGM_N2_L6S1_2<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/2-7-2.geojson")
Center_2DGM_N2_L6S1_3<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/2-7-3.geojson")
Center_2DGM_N2_L6S1_4<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/2-7-4.geojson")
Center_2DGM_N2_L6S1_5<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/2-7-5.geojson")
Center_2DGM_N2_L6S1_6<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/2-7-6.geojson")
Center_2DGM_N2_L6S1_7<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/2-7-7.geojson")

Center_2DGM_N2_S2_4_1<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/2-8-1.geojson")
Center_2DGM_N2_S2_4_2<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/2-8-2.geojson")
Center_2DGM_N2_S2_4_3<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/2-8-3.geojson")
Center_2DGM_N2_S2_4_4<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/2-8-4.geojson")
Center_2DGM_N2_S2_4_5<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/2-8-5.geojson")
Center_2DGM_N2_S2_4_6<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/2-8-6.geojson")
Center_2DGM_N2_S2_4_7<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/2-8-7.geojson")


# 2DGMN3
Center_2DGM_N3_T1_4_1<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/3-1-1.geojson")
Center_2DGM_N3_T1_4_2<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/3-1-2.geojson")
Center_2DGM_N3_T1_4_3<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/3-1-3.geojson")
Center_2DGM_N3_T1_4_4<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/3-1-4.geojson")
Center_2DGM_N3_T1_4_5<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/3-1-5.geojson")
Center_2DGM_N3_T1_4_6<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/3-1-6.geojson")
Center_2DGM_N3_T1_4_7<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/3-1-7.geojson")
Center_2DGM_N3_T1_4_8<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/3-1-8.geojson")
Center_2DGM_N3_T1_4_9<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/3-1-9.geojson")
Center_2DGM_N3_T1_4_10<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/3-1-10.geojson")

Center_2DGM_N3_T5_7_1<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/3-2-1.geojson")
Center_2DGM_N3_T5_7_2<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/3-2-2.geojson")
Center_2DGM_N3_T5_7_3<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/3-2-3.geojson")
Center_2DGM_N3_T5_7_4<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/3-2-4.geojson")
Center_2DGM_N3_T5_7_5<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/3-2-5.geojson")
Center_2DGM_N3_T5_7_6<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/3-2-6.geojson")
Center_2DGM_N3_T5_7_7<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/3-2-7.geojson")
Center_2DGM_N3_T5_7_8<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/3-2-8.geojson")
Center_2DGM_N3_T5_7_9<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/3-2-9.geojson")
Center_2DGM_N3_T5_7_10<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/3-2-10.geojson")

Center_2DGM_N3_T8_10_1<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/3-3-1.geojson")
Center_2DGM_N3_T8_10_2<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/3-3-2.geojson")
Center_2DGM_N3_T8_10_3<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/3-3-3.geojson")
Center_2DGM_N3_T8_10_4<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/3-3-4.geojson")
Center_2DGM_N3_T8_10_5<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/3-3-5.geojson")
Center_2DGM_N3_T8_10_6<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/3-3-6.geojson")
Center_2DGM_N3_T8_10_7<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/3-3-7.geojson")
Center_2DGM_N3_T8_10_8<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/3-3-8.geojson")
Center_2DGM_N3_T8_10_9<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/3-3-9.geojson")
Center_2DGM_N3_T8_10_10<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/3-3-10.geojson")

Center_2DGM_N3_T11_13_1<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/3-4-1.geojson")
Center_2DGM_N3_T11_13_2<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/3-4-2.geojson")
Center_2DGM_N3_T11_13_3<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/3-4-3.geojson")
Center_2DGM_N3_T11_13_4<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/3-4-4.geojson")
Center_2DGM_N3_T11_13_5<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/3-4-5.geojson")
Center_2DGM_N3_T11_13_6<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/3-4-6.geojson")
Center_2DGM_N3_T11_13_7<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/3-4-7.geojson")
Center_2DGM_N3_T11_13_8<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/3-4-8.geojson")

Center_2DGM_N3_L1_3_1<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/3-5-1.geojson")
Center_2DGM_N3_L1_3_2<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/3-5-2.geojson")
Center_2DGM_N3_L1_3_3<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/3-5-3.geojson")
Center_2DGM_N3_L1_3_4<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/3-5-4.geojson")
Center_2DGM_N3_L1_3_5<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/3-5-5.geojson")
Center_2DGM_N3_L1_3_6<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/3-5-6.geojson")
Center_2DGM_N3_L1_3_7<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/3-5-7.geojson")
Center_2DGM_N3_L1_3_8<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/3-5-8.geojson")
Center_2DGM_N3_L1_3_9<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/3-5-9.geojson")

Center_2DGM_N3_L45_1<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/3-6-1.geojson")
Center_2DGM_N3_L45_2<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/3-6-2.geojson")

Center_2DGM_N3_L6S1_1<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/3-7-1.geojson")
Center_2DGM_N3_L6S1_2<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/3-7-2.geojson")
Center_2DGM_N3_L6S1_3<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/3-7-3.geojson")
Center_2DGM_N3_L6S1_4<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/3-7-4.geojson")

Center_2DGM_N3_S2_4_1<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/3-8-1.geojson")
Center_2DGM_N3_S2_4_2<- geojson_sf("./Xenium_SC/ROI_geojson/2DGM_center/3-8-2.geojson")

# CtrlFN1
Center_CtrlF_N1_T1_4_2<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/1-1-2.geojson")
Center_CtrlF_N1_T1_4_3<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/1-1-3.geojson")
Center_CtrlF_N1_T1_4_4<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/1-1-4.geojson")
Center_CtrlF_N1_T1_4_5<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/1-1-5.geojson")
Center_CtrlF_N1_T1_4_6<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/1-1-6.geojson")
Center_CtrlF_N1_T1_4_7<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/1-1-7.geojson")
Center_CtrlF_N1_T1_4_8<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/1-1-8.geojson")
Center_CtrlF_N1_T1_4_9<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/1-1-9.geojson")
Center_CtrlF_N1_T1_4_10<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/1-1-10.geojson")


Center_CtrlF_N1_T5_7_1<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/1-2-1.geojson")
Center_CtrlF_N1_T5_7_2<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/1-2-2.geojson")
Center_CtrlF_N1_T5_7_3<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/1-2-3.geojson")
Center_CtrlF_N1_T5_7_4<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/1-2-4.geojson")
Center_CtrlF_N1_T5_7_5<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/1-2-5.geojson")
Center_CtrlF_N1_T5_7_6<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/1-2-6.geojson")
Center_CtrlF_N1_T5_7_7<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/1-2-7.geojson")
Center_CtrlF_N1_T5_7_8<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/1-2-8.geojson")

Center_CtrlF_N1_T8_10_1<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/1-3-1.geojson")
Center_CtrlF_N1_T8_10_2<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/1-3-2.geojson")
Center_CtrlF_N1_T8_10_3<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/1-3-3.geojson")
Center_CtrlF_N1_T8_10_4<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/1-3-4.geojson")
Center_CtrlF_N1_T8_10_5<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/1-3-5.geojson")
Center_CtrlF_N1_T8_10_6<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/1-3-6.geojson")
Center_CtrlF_N1_T8_10_7<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/1-3-7.geojson")
Center_CtrlF_N1_T8_10_8<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/1-3-8.geojson")
Center_CtrlF_N1_T8_10_9<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/1-3-9.geojson")


Center_CtrlF_N1_T11_13_1<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/1-4-1.geojson")
Center_CtrlF_N1_T11_13_2<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/1-4-2.geojson")
Center_CtrlF_N1_T11_13_3<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/1-4-3.geojson")
Center_CtrlF_N1_T11_13_4<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/1-4-4.geojson")
Center_CtrlF_N1_T11_13_5<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/1-4-5.geojson")
Center_CtrlF_N1_T11_13_6<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/1-4-6.geojson")
Center_CtrlF_N1_T11_13_7<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/1-4-7.geojson")
Center_CtrlF_N1_T11_13_8<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/1-4-8.geojson")

Center_CtrlF_N1_L1_3_1<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/1-5-1.geojson")
Center_CtrlF_N1_L1_3_2<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/1-5-2.geojson")
Center_CtrlF_N1_L1_3_3<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/1-5-3.geojson")
Center_CtrlF_N1_L1_3_4<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/1-5-4.geojson")
Center_CtrlF_N1_L1_3_5<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/1-5-5.geojson")
Center_CtrlF_N1_L1_3_6<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/1-5-6.geojson")
Center_CtrlF_N1_L1_3_7<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/1-5-7.geojson")
Center_CtrlF_N1_L1_3_8<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/1-5-8.geojson")
Center_CtrlF_N1_L1_3_9<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/1-5-9.geojson")


Center_CtrlF_N1_L45_1<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/1-6-1.geojson")
Center_CtrlF_N1_L45_2<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/1-6-2.geojson")
Center_CtrlF_N1_L45_3<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/1-6-3.geojson")
Center_CtrlF_N1_L45_4<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/1-6-4.geojson")
Center_CtrlF_N1_L45_5<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/1-6-5.geojson")


Center_CtrlF_N1_L6S1_1<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/1-7-1.geojson")
Center_CtrlF_N1_L6S1_2<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/1-7-2.geojson")
Center_CtrlF_N1_L6S1_3<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/1-7-3.geojson")
Center_CtrlF_N1_L6S1_4<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/1-7-4.geojson")
Center_CtrlF_N1_L6S1_5<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/1-7-5.geojson")
Center_CtrlF_N1_L6S1_6<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/1-7-6.geojson")

Center_CtrlF_N1_S2_4_1<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/1-8-1.geojson")
Center_CtrlF_N1_S2_4_2<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/1-8-2.geojson")
Center_CtrlF_N1_S2_4_3<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/1-8-3.geojson")
Center_CtrlF_N1_S2_4_4<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/1-8-4.geojson")
Center_CtrlF_N1_S2_4_5<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/1-8-5.geojson")



# CtrlFN2
Center_CtrlF_N2_T1_4_1<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/2-1-1.geojson")
Center_CtrlF_N2_T1_4_2<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/2-1-2.geojson")
Center_CtrlF_N2_T1_4_3<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/2-1-3.geojson")
Center_CtrlF_N2_T1_4_4<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/2-1-4.geojson")
Center_CtrlF_N2_T1_4_5<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/2-1-5.geojson")
Center_CtrlF_N2_T1_4_6<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/2-1-6.geojson")
Center_CtrlF_N2_T1_4_7<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/2-1-7.geojson")
Center_CtrlF_N2_T1_4_8<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/2-1-8.geojson")
Center_CtrlF_N2_T1_4_9<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/2-1-9.geojson")
Center_CtrlF_N2_T1_4_10<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/2-1-10.geojson")
Center_CtrlF_N2_T1_4_11<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/2-1-11.geojson")


Center_CtrlF_N2_T5_7_1<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/2-2-1.geojson")
Center_CtrlF_N2_T5_7_2<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/2-2-2.geojson")
Center_CtrlF_N2_T5_7_3<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/2-2-3.geojson")
Center_CtrlF_N2_T5_7_4<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/2-2-4.geojson")
Center_CtrlF_N2_T5_7_5<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/2-2-5.geojson")
Center_CtrlF_N2_T5_7_6<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/2-2-6.geojson")
Center_CtrlF_N2_T5_7_7<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/2-2-7.geojson")
Center_CtrlF_N2_T5_7_8<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/2-2-8.geojson")
Center_CtrlF_N2_T5_7_9<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/2-2-9.geojson")


Center_CtrlF_N2_T8_10_1<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/2-3-1.geojson")
Center_CtrlF_N2_T8_10_2<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/2-3-2.geojson")
Center_CtrlF_N2_T8_10_3<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/2-3-3.geojson")
Center_CtrlF_N2_T8_10_4<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/2-3-4.geojson")
Center_CtrlF_N2_T8_10_5<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/2-3-5.geojson")
Center_CtrlF_N2_T8_10_6<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/2-3-6.geojson")
Center_CtrlF_N2_T8_10_7<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/2-3-7.geojson")
Center_CtrlF_N2_T8_10_8<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/2-3-8.geojson")
Center_CtrlF_N2_T8_10_9<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/2-3-9.geojson")

Center_CtrlF_N2_T11_13_1<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/2-4-1.geojson")
Center_CtrlF_N2_T11_13_2<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/2-4-2.geojson")
Center_CtrlF_N2_T11_13_3<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/2-4-3.geojson")
Center_CtrlF_N2_T11_13_4<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/2-4-4.geojson")
Center_CtrlF_N2_T11_13_5<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/2-4-5.geojson")
Center_CtrlF_N2_T11_13_6<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/2-4-6.geojson")
Center_CtrlF_N2_T11_13_7<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/2-4-7.geojson")
Center_CtrlF_N2_T11_13_8<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/2-4-8.geojson")

Center_CtrlF_N2_L1_3_1<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/2-5-1.geojson")
Center_CtrlF_N2_L1_3_2<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/2-5-2.geojson")
Center_CtrlF_N2_L1_3_3<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/2-5-3.geojson")
Center_CtrlF_N2_L1_3_4<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/2-5-4.geojson")
Center_CtrlF_N2_L1_3_5<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/2-5-5.geojson")
Center_CtrlF_N2_L1_3_6<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/2-5-6.geojson")
Center_CtrlF_N2_L1_3_7<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/2-5-7.geojson")
Center_CtrlF_N2_L1_3_8<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/2-5-8.geojson")
Center_CtrlF_N2_L1_3_9<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/2-5-9.geojson")

Center_CtrlF_N2_L45_1<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/2-6-1.geojson")
Center_CtrlF_N2_L45_2<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/2-6-2.geojson")
Center_CtrlF_N2_L45_3<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/2-6-3.geojson")
Center_CtrlF_N2_L45_4<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/2-6-4.geojson")
Center_CtrlF_N2_L45_5<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/2-6-5.geojson")

Center_CtrlF_N2_L6S1_1<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/2-7-1.geojson")
Center_CtrlF_N2_L6S1_2<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/2-7-2.geojson")
Center_CtrlF_N2_L6S1_3<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/2-7-3.geojson")
Center_CtrlF_N2_L6S1_4<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/2-7-4.geojson")
Center_CtrlF_N2_L6S1_5<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/2-7-5.geojson")
Center_CtrlF_N2_L6S1_6<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/2-7-6.geojson")

Center_CtrlF_N2_S2_4_1<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/2-8-1.geojson")
Center_CtrlF_N2_S2_4_2<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/2-8-2.geojson")
Center_CtrlF_N2_S2_4_3<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/2-8-3.geojson")
Center_CtrlF_N2_S2_4_4<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/2-8-4.geojson")
Center_CtrlF_N2_S2_4_5<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/2-8-5.geojson")
Center_CtrlF_N2_S2_4_6<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/2-8-6.geojson")

# CtrlFN3
Center_CtrlF_N3_T1_4_1<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/3-1-1.geojson")
Center_CtrlF_N3_T1_4_2<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/3-1-2.geojson")
Center_CtrlF_N3_T1_4_3<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/3-1-3.geojson")
Center_CtrlF_N3_T1_4_4<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/3-1-4.geojson")
Center_CtrlF_N3_T1_4_5<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/3-1-5.geojson")
Center_CtrlF_N3_T1_4_6<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/3-1-6.geojson")
Center_CtrlF_N3_T1_4_7<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/3-1-7.geojson")
Center_CtrlF_N3_T1_4_8<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/3-1-8.geojson")
Center_CtrlF_N3_T1_4_9<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/3-1-9.geojson")
Center_CtrlF_N3_T1_4_10<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/3-1-10.geojson")
Center_CtrlF_N3_T1_4_11<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/3-1-11.geojson")


Center_CtrlF_N3_T5_7_1<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/3-2-1.geojson")
Center_CtrlF_N3_T5_7_2<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/3-2-2.geojson")
Center_CtrlF_N3_T5_7_3<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/3-2-3.geojson")
Center_CtrlF_N3_T5_7_4<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/3-2-4.geojson")
Center_CtrlF_N3_T5_7_5<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/3-2-5.geojson")
Center_CtrlF_N3_T5_7_6<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/3-2-6.geojson")
Center_CtrlF_N3_T5_7_7<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/3-2-7.geojson")
Center_CtrlF_N3_T5_7_8<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/3-2-8.geojson")

Center_CtrlF_N3_T8_10_1<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/3-3-1.geojson")
Center_CtrlF_N3_T8_10_2<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/3-3-2.geojson")
Center_CtrlF_N3_T8_10_3<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/3-3-3.geojson")
Center_CtrlF_N3_T8_10_4<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/3-3-4.geojson")
Center_CtrlF_N3_T8_10_5<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/3-3-5.geojson")
Center_CtrlF_N3_T8_10_6<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/3-3-6.geojson")
Center_CtrlF_N3_T8_10_7<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/3-3-7.geojson")
Center_CtrlF_N3_T8_10_8<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/3-3-8.geojson")

Center_CtrlF_N3_T11_13_1<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/3-4-1.geojson")
Center_CtrlF_N3_T11_13_2<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/3-4-2.geojson")
Center_CtrlF_N3_T11_13_3<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/3-4-3.geojson")
Center_CtrlF_N3_T11_13_4<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/3-4-4.geojson")
Center_CtrlF_N3_T11_13_5<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/3-4-5.geojson")
Center_CtrlF_N3_T11_13_6<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/3-4-6.geojson")
Center_CtrlF_N3_T11_13_7<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/3-4-7.geojson")
Center_CtrlF_N3_T11_13_8<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/3-4-8.geojson")

Center_CtrlF_N3_L1_3_1<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/3-5-1.geojson")
Center_CtrlF_N3_L1_3_2<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/3-5-2.geojson")
Center_CtrlF_N3_L1_3_3<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/3-5-3.geojson")
Center_CtrlF_N3_L1_3_4<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/3-5-4.geojson")
Center_CtrlF_N3_L1_3_5<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/3-5-5.geojson")
Center_CtrlF_N3_L1_3_6<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/3-5-6.geojson")
Center_CtrlF_N3_L1_3_7<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/3-5-7.geojson")
Center_CtrlF_N3_L1_3_8<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/3-5-8.geojson")
Center_CtrlF_N3_L1_3_9<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/3-5-9.geojson")


Center_CtrlF_N3_L45_1<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/3-6-1.geojson")
Center_CtrlF_N3_L45_2<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/3-6-2.geojson")
Center_CtrlF_N3_L45_3<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/3-6-3.geojson")
Center_CtrlF_N3_L45_4<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/3-6-4.geojson")
Center_CtrlF_N3_L45_5<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/3-6-5.geojson")

Center_CtrlF_N3_L6S1_1<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/3-7-1.geojson")
Center_CtrlF_N3_L6S1_2<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/3-7-2.geojson")
Center_CtrlF_N3_L6S1_3<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/3-7-3.geojson")
Center_CtrlF_N3_L6S1_4<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/3-7-4.geojson")
Center_CtrlF_N3_L6S1_5<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/3-7-5.geojson")
Center_CtrlF_N3_L6S1_6<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/3-7-6.geojson")

Center_CtrlF_N3_S2_4_1<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/3-8-1.geojson")
Center_CtrlF_N3_S2_4_2<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/3-8-2.geojson")
Center_CtrlF_N3_S2_4_3<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/3-8-3.geojson")
Center_CtrlF_N3_S2_4_4<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/3-8-4.geojson")
Center_CtrlF_N3_S2_4_5<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/3-8-5.geojson")
Center_CtrlF_N3_S2_4_6<- geojson_sf("./Xenium_SC/ROI_geojson/CtrlF_center/3-8-6.geojson")


# ColdFN1
Center_ColdF_N1_T1_4_1<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/1-1-1.geojson")
Center_ColdF_N1_T1_4_2<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/1-1-2.geojson")
Center_ColdF_N1_T1_4_3<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/1-1-3.geojson")
Center_ColdF_N1_T1_4_4<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/1-1-4.geojson")
Center_ColdF_N1_T1_4_5<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/1-1-5.geojson")
Center_ColdF_N1_T1_4_6<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/1-1-6.geojson")
Center_ColdF_N1_T1_4_7<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/1-1-7.geojson")
Center_ColdF_N1_T1_4_8<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/1-1-8.geojson")
Center_ColdF_N1_T1_4_9<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/1-1-9.geojson")

Center_ColdF_N1_T5_7_1<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/1-2-1.geojson")
Center_ColdF_N1_T5_7_2<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/1-2-2.geojson")
Center_ColdF_N1_T5_7_3<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/1-2-3.geojson")
Center_ColdF_N1_T5_7_4<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/1-2-4.geojson")
Center_ColdF_N1_T5_7_5<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/1-2-5.geojson")
Center_ColdF_N1_T5_7_6<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/1-2-6.geojson")
Center_ColdF_N1_T5_7_7<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/1-2-7.geojson")
Center_ColdF_N1_T5_7_8<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/1-2-8.geojson")


Center_ColdF_N1_T8_10_1<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/1-3-1.geojson")
Center_ColdF_N1_T8_10_2<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/1-3-2.geojson")
Center_ColdF_N1_T8_10_3<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/1-3-3.geojson")
Center_ColdF_N1_T8_10_4<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/1-3-4.geojson")
Center_ColdF_N1_T8_10_5<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/1-3-5.geojson")
Center_ColdF_N1_T8_10_6<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/1-3-6.geojson")
Center_ColdF_N1_T8_10_7<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/1-3-7.geojson")
Center_ColdF_N1_T8_10_8<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/1-3-8.geojson")


Center_ColdF_N1_T11_13_1<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/1-4-1.geojson")
Center_ColdF_N1_T11_13_2<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/1-4-2.geojson")
Center_ColdF_N1_T11_13_3<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/1-4-3.geojson")
Center_ColdF_N1_T11_13_4<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/1-4-4.geojson")
Center_ColdF_N1_T11_13_5<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/1-4-5.geojson")
Center_ColdF_N1_T11_13_6<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/1-4-6.geojson")
Center_ColdF_N1_T11_13_7<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/1-4-7.geojson")
Center_ColdF_N1_T11_13_8<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/1-4-8.geojson")

Center_ColdF_N1_L1_3_1<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/1-5-1.geojson")
Center_ColdF_N1_L1_3_2<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/1-5-2.geojson")
Center_ColdF_N1_L1_3_3<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/1-5-3.geojson")
Center_ColdF_N1_L1_3_4<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/1-5-4.geojson")
Center_ColdF_N1_L1_3_5<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/1-5-5.geojson")
Center_ColdF_N1_L1_3_6<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/1-5-6.geojson")
Center_ColdF_N1_L1_3_7<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/1-5-7.geojson")
Center_ColdF_N1_L1_3_8<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/1-5-8.geojson")
Center_ColdF_N1_L1_3_9<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/1-5-9.geojson")
Center_ColdF_N1_L1_3_10<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/1-5-10.geojson")

Center_ColdF_N1_L45_1<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/1-6-1.geojson")
Center_ColdF_N1_L45_2<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/1-6-2.geojson")
Center_ColdF_N1_L45_3<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/1-6-3.geojson")
Center_ColdF_N1_L45_4<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/1-6-4.geojson")
Center_ColdF_N1_L45_5<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/1-6-5.geojson")
Center_ColdF_N1_L45_6<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/1-6-6.geojson")


Center_ColdF_N1_L6S1_1<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/1-7-1.geojson")
Center_ColdF_N1_L6S1_2<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/1-7-2.geojson")
Center_ColdF_N1_L6S1_3<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/1-7-3.geojson")
Center_ColdF_N1_L6S1_4<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/1-7-4.geojson")
Center_ColdF_N1_L6S1_5<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/1-7-5.geojson")
Center_ColdF_N1_L6S1_6<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/1-7-6.geojson")

Center_ColdF_N1_S2_4_1<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/1-8-1.geojson")
Center_ColdF_N1_S2_4_2<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/1-8-2.geojson")
Center_ColdF_N1_S2_4_3<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/1-8-3.geojson")
Center_ColdF_N1_S2_4_4<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/1-8-4.geojson")
Center_ColdF_N1_S2_4_5<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/1-8-5.geojson")



# ColdFN2
Center_ColdF_N2_T1_4_1<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/2-1-1.geojson")
Center_ColdF_N2_T1_4_2<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/2-1-2.geojson")
Center_ColdF_N2_T1_4_3<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/2-1-3.geojson")
Center_ColdF_N2_T1_4_4<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/2-1-4.geojson")
Center_ColdF_N2_T1_4_5<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/2-1-5.geojson")
Center_ColdF_N2_T1_4_6<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/2-1-6.geojson")
Center_ColdF_N2_T1_4_7<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/2-1-7.geojson")
Center_ColdF_N2_T1_4_8<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/2-1-8.geojson")
Center_ColdF_N2_T1_4_9<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/2-1-9.geojson")

Center_ColdF_N2_T5_7_1<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/2-2-1.geojson")
Center_ColdF_N2_T5_7_2<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/2-2-2.geojson")
Center_ColdF_N2_T5_7_3<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/2-2-3.geojson")
Center_ColdF_N2_T5_7_4<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/2-2-4.geojson")
Center_ColdF_N2_T5_7_5<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/2-2-5.geojson")
Center_ColdF_N2_T5_7_6<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/2-2-6.geojson")
Center_ColdF_N2_T5_7_7<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/2-2-7.geojson")

Center_ColdF_N2_T8_10_1<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/2-3-1.geojson")
Center_ColdF_N2_T8_10_2<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/2-3-2.geojson")
Center_ColdF_N2_T8_10_3<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/2-3-3.geojson")
Center_ColdF_N2_T8_10_4<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/2-3-4.geojson")
Center_ColdF_N2_T8_10_5<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/2-3-5.geojson")
Center_ColdF_N2_T8_10_6<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/2-3-6.geojson")
Center_ColdF_N2_T8_10_7<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/2-3-7.geojson")
Center_ColdF_N2_T8_10_8<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/2-3-8.geojson")

Center_ColdF_N2_T11_13_1<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/2-4-1.geojson")
Center_ColdF_N2_T11_13_2<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/2-4-2.geojson")
Center_ColdF_N2_T11_13_3<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/2-4-3.geojson")
Center_ColdF_N2_T11_13_4<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/2-4-4.geojson")
Center_ColdF_N2_T11_13_5<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/2-4-5.geojson")
Center_ColdF_N2_T11_13_6<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/2-4-6.geojson")
Center_ColdF_N2_T11_13_7<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/2-4-7.geojson")
Center_ColdF_N2_T11_13_8<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/2-4-8.geojson")

Center_ColdF_N2_L1_3_1<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/2-5-1.geojson")
Center_ColdF_N2_L1_3_2<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/2-5-2.geojson")
Center_ColdF_N2_L1_3_3<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/2-5-3.geojson")
Center_ColdF_N2_L1_3_4<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/2-5-4.geojson")
Center_ColdF_N2_L1_3_5<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/2-5-5.geojson")
Center_ColdF_N2_L1_3_6<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/2-5-6.geojson")
Center_ColdF_N2_L1_3_7<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/2-5-7.geojson")
Center_ColdF_N2_L1_3_8<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/2-5-8.geojson")
Center_ColdF_N2_L1_3_9<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/2-5-9.geojson")
Center_ColdF_N2_L1_3_10<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/2-5-10.geojson")


Center_ColdF_N2_L45_1<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/2-6-1.geojson")
Center_ColdF_N2_L45_2<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/2-6-2.geojson")
Center_ColdF_N2_L45_3<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/2-6-3.geojson")
Center_ColdF_N2_L45_4<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/2-6-4.geojson")
Center_ColdF_N2_L45_5<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/2-6-5.geojson")

Center_ColdF_N2_L6S1_1<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/2-7-1.geojson")
Center_ColdF_N2_L6S1_2<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/2-7-2.geojson")
Center_ColdF_N2_L6S1_3<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/2-7-3.geojson")
Center_ColdF_N2_L6S1_4<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/2-7-4.geojson")
Center_ColdF_N2_L6S1_5<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/2-7-5.geojson")
Center_ColdF_N2_L6S1_6<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/2-7-6.geojson")

Center_ColdF_N2_S2_4_1<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/2-8-1.geojson")
Center_ColdF_N2_S2_4_2<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/2-8-2.geojson")
Center_ColdF_N2_S2_4_3<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/2-8-3.geojson")
Center_ColdF_N2_S2_4_4<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/2-8-4.geojson")
Center_ColdF_N2_S2_4_5<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/2-8-5.geojson")

# ColdFN3
Center_ColdF_N3_T1_4_1<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/3-1-1.geojson")
Center_ColdF_N3_T1_4_2<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/3-1-2.geojson")
Center_ColdF_N3_T1_4_3<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/3-1-3.geojson")
Center_ColdF_N3_T1_4_4<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/3-1-4.geojson")
Center_ColdF_N3_T1_4_5<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/3-1-5.geojson")
Center_ColdF_N3_T1_4_6<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/3-1-6.geojson")
Center_ColdF_N3_T1_4_7<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/3-1-7.geojson")
Center_ColdF_N3_T1_4_8<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/3-1-8.geojson")

Center_ColdF_N3_T5_7_1<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/3-2-1.geojson")
Center_ColdF_N3_T5_7_2<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/3-2-2.geojson")
Center_ColdF_N3_T5_7_3<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/3-2-3.geojson")
Center_ColdF_N3_T5_7_4<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/3-2-4.geojson")
Center_ColdF_N3_T5_7_5<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/3-2-5.geojson")
Center_ColdF_N3_T5_7_6<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/3-2-6.geojson")
Center_ColdF_N3_T5_7_7<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/3-2-7.geojson")
Center_ColdF_N3_T5_7_8<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/3-2-8.geojson")

Center_ColdF_N3_T8_10_1<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/3-3-1.geojson")
Center_ColdF_N3_T8_10_2<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/3-3-2.geojson")
Center_ColdF_N3_T8_10_3<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/3-3-3.geojson")
Center_ColdF_N3_T8_10_4<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/3-3-4.geojson")
Center_ColdF_N3_T8_10_5<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/3-3-5.geojson")
Center_ColdF_N3_T8_10_6<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/3-3-6.geojson")
Center_ColdF_N3_T8_10_7<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/3-3-7.geojson")

Center_ColdF_N3_T11_13_1<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/3-4-1.geojson")
Center_ColdF_N3_T11_13_2<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/3-4-2.geojson")
Center_ColdF_N3_T11_13_3<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/3-4-3.geojson")
Center_ColdF_N3_T11_13_4<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/3-4-4.geojson")
Center_ColdF_N3_T11_13_5<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/3-4-5.geojson")
Center_ColdF_N3_T11_13_6<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/3-4-6.geojson")
Center_ColdF_N3_T11_13_7<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/3-4-7.geojson")

Center_ColdF_N3_L1_3_1<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/3-5-1.geojson")
Center_ColdF_N3_L1_3_2<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/3-5-2.geojson")
Center_ColdF_N3_L1_3_3<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/3-5-3.geojson")
Center_ColdF_N3_L1_3_4<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/3-5-4.geojson")
Center_ColdF_N3_L1_3_5<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/3-5-5.geojson")
Center_ColdF_N3_L1_3_6<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/3-5-6.geojson")
Center_ColdF_N3_L1_3_7<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/3-5-7.geojson")
Center_ColdF_N3_L1_3_8<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/3-5-8.geojson")
Center_ColdF_N3_L1_3_9<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/3-5-9.geojson")

Center_ColdF_N3_L45_1<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/3-6-1.geojson")
Center_ColdF_N3_L45_2<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/3-6-2.geojson")
Center_ColdF_N3_L45_3<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/3-6-3.geojson")
Center_ColdF_N3_L45_4<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/3-6-4.geojson")
Center_ColdF_N3_L45_5<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/3-6-5.geojson")


Center_ColdF_N3_L6S1_1<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/3-7-1.geojson")
Center_ColdF_N3_L6S1_2<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/3-7-2.geojson")
Center_ColdF_N3_L6S1_3<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/3-7-3.geojson")
Center_ColdF_N3_L6S1_4<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/3-7-4.geojson")
Center_ColdF_N3_L6S1_5<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/3-7-5.geojson")
Center_ColdF_N3_L6S1_6<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/3-7-6.geojson")

Center_ColdF_N3_S2_4_1<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/3-8-1.geojson")
Center_ColdF_N3_S2_4_2<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/3-8-2.geojson")
Center_ColdF_N3_S2_4_3<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/3-8-3.geojson")
Center_ColdF_N3_S2_4_4<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/3-8-4.geojson")
Center_ColdF_N3_S2_4_5<- geojson_sf("./Xenium_SC/ROI_geojson/ColdF_center/3-8-5.geojson")






# CtrlN1
Center_Ctrl_N1_T1_4_1<- geojson_sf("./Xenium_SC/ROI_geojson/Ctrl_center/1-1-1.geojson")
Center_Ctrl_N1_T1_4_2<- geojson_sf("./Xenium_SC/ROI_geojson/Ctrl_center/1-1-2.geojson")
Center_Ctrl_N1_T1_4_3<- geojson_sf("./Xenium_SC/ROI_geojson/Ctrl_center/1-1-3.geojson")

Center_Ctrl_N1_T5_7_1<- geojson_sf("./Xenium_SC/ROI_geojson/Ctrl_center/1-2-1.geojson")
Center_Ctrl_N1_T5_7_2<- geojson_sf("./Xenium_SC/ROI_geojson/Ctrl_center/1-2-2.geojson")
Center_Ctrl_N1_T5_7_3<- geojson_sf("./Xenium_SC/ROI_geojson/Ctrl_center/1-2-3.geojson")
Center_Ctrl_N1_T5_7_4<- geojson_sf("./Xenium_SC/ROI_geojson/Ctrl_center/1-2-4.geojson")

Center_Ctrl_N1_T8_10_1<- geojson_sf("./Xenium_SC/ROI_geojson/Ctrl_center/1-3-1.geojson")
Center_Ctrl_N1_T8_10_2<- geojson_sf("./Xenium_SC/ROI_geojson/Ctrl_center/1-3-2.geojson")
Center_Ctrl_N1_T8_10_3<- geojson_sf("./Xenium_SC/ROI_geojson/Ctrl_center/1-3-3.geojson")
Center_Ctrl_N1_T8_10_4<- geojson_sf("./Xenium_SC/ROI_geojson/Ctrl_center/1-3-4.geojson")

Center_Ctrl_N1_T11_13_1<- geojson_sf("./Xenium_SC/ROI_geojson/Ctrl_center/1-4-1.geojson")
Center_Ctrl_N1_T11_13_2<- geojson_sf("./Xenium_SC/ROI_geojson/Ctrl_center/1-4-2.geojson")
Center_Ctrl_N1_T11_13_3<- geojson_sf("./Xenium_SC/ROI_geojson/Ctrl_center/1-4-3.geojson")
Center_Ctrl_N1_T11_13_4<- geojson_sf("./Xenium_SC/ROI_geojson/Ctrl_center/1-4-4.geojson")
Center_Ctrl_N1_T11_13_5<- geojson_sf("./Xenium_SC/ROI_geojson/Ctrl_center/1-4-5.geojson")

Center_Ctrl_N1_L1_3_1<- geojson_sf("./Xenium_SC/ROI_geojson/Ctrl_center/1-5-1.geojson")
Center_Ctrl_N1_L1_3_2<- geojson_sf("./Xenium_SC/ROI_geojson/Ctrl_center/1-5-2.geojson")
Center_Ctrl_N1_L1_3_3<- geojson_sf("./Xenium_SC/ROI_geojson/Ctrl_center/1-5-3.geojson")
Center_Ctrl_N1_L1_3_4<- geojson_sf("./Xenium_SC/ROI_geojson/Ctrl_center/1-5-4.geojson")
Center_Ctrl_N1_L1_3_5<- geojson_sf("./Xenium_SC/ROI_geojson/Ctrl_center/1-5-5.geojson")
Center_Ctrl_N1_L1_3_6<- geojson_sf("./Xenium_SC/ROI_geojson/Ctrl_center/1-5-6.geojson")

Center_Ctrl_N1_L45_1<- geojson_sf("./Xenium_SC/ROI_geojson/Ctrl_center/1-6-1.geojson")
Center_Ctrl_N1_L45_2<- geojson_sf("./Xenium_SC/ROI_geojson/Ctrl_center/1-6-2.geojson")
Center_Ctrl_N1_L45_3<- geojson_sf("./Xenium_SC/ROI_geojson/Ctrl_center/1-6-3.geojson")

Center_Ctrl_N1_L6S1_1<- geojson_sf("./Xenium_SC/ROI_geojson/Ctrl_center/1-7-1.geojson")
Center_Ctrl_N1_L6S1_2<- geojson_sf("./Xenium_SC/ROI_geojson/Ctrl_center/1-7-2.geojson")
Center_Ctrl_N1_L6S1_3<- geojson_sf("./Xenium_SC/ROI_geojson/Ctrl_center/1-7-3.geojson")

Center_Ctrl_N1_S2_4_1<- geojson_sf("./Xenium_SC/ROI_geojson/Ctrl_center/1-8-1.geojson")

# CtrlN2
Center_Ctrl_N2_T1_4_1<- geojson_sf("./Xenium_SC/ROI_geojson/Ctrl_center/2-1-1.geojson")
Center_Ctrl_N2_T1_4_2<- geojson_sf("./Xenium_SC/ROI_geojson/Ctrl_center/2-1-2.geojson")
Center_Ctrl_N2_T1_4_3<- geojson_sf("./Xenium_SC/ROI_geojson/Ctrl_center/2-1-3.geojson")
Center_Ctrl_N2_T1_4_4<- geojson_sf("./Xenium_SC/ROI_geojson/Ctrl_center/2-1-4.geojson")
Center_Ctrl_N2_T1_4_5<- geojson_sf("./Xenium_SC/ROI_geojson/Ctrl_center/2-1-5.geojson")
Center_Ctrl_N2_T1_4_6<- geojson_sf("./Xenium_SC/ROI_geojson/Ctrl_center/2-1-6.geojson")

Center_Ctrl_N2_T5_7_1<- geojson_sf("./Xenium_SC/ROI_geojson/Ctrl_center/2-2-1.geojson")
Center_Ctrl_N2_T5_7_2<- geojson_sf("./Xenium_SC/ROI_geojson/Ctrl_center/2-2-2.geojson")
Center_Ctrl_N2_T5_7_3<- geojson_sf("./Xenium_SC/ROI_geojson/Ctrl_center/2-2-3.geojson")
Center_Ctrl_N2_T5_7_4<- geojson_sf("./Xenium_SC/ROI_geojson/Ctrl_center/2-2-4.geojson")
Center_Ctrl_N2_T5_7_5<- geojson_sf("./Xenium_SC/ROI_geojson/Ctrl_center/2-2-5.geojson")
Center_Ctrl_N2_T5_7_6<- geojson_sf("./Xenium_SC/ROI_geojson/Ctrl_center/2-2-6.geojson")

Center_Ctrl_N2_T8_10_1<- geojson_sf("./Xenium_SC/ROI_geojson/Ctrl_center/2-3-1.geojson")
Center_Ctrl_N2_T8_10_2<- geojson_sf("./Xenium_SC/ROI_geojson/Ctrl_center/2-3-2.geojson")
Center_Ctrl_N2_T8_10_3<- geojson_sf("./Xenium_SC/ROI_geojson/Ctrl_center/2-3-3.geojson")
Center_Ctrl_N2_T8_10_4<- geojson_sf("./Xenium_SC/ROI_geojson/Ctrl_center/2-3-4.geojson")
Center_Ctrl_N2_T8_10_5<- geojson_sf("./Xenium_SC/ROI_geojson/Ctrl_center/2-3-5.geojson")
Center_Ctrl_N2_T8_10_6<- geojson_sf("./Xenium_SC/ROI_geojson/Ctrl_center/2-3-6.geojson")
Center_Ctrl_N2_T8_10_7<- geojson_sf("./Xenium_SC/ROI_geojson/Ctrl_center/2-3-7.geojson")
Center_Ctrl_N2_T8_10_8<- geojson_sf("./Xenium_SC/ROI_geojson/Ctrl_center/2-3-8.geojson")

Center_Ctrl_N2_T11_13_1<- geojson_sf("./Xenium_SC/ROI_geojson/Ctrl_center/2-4-1.geojson")
Center_Ctrl_N2_T11_13_2<- geojson_sf("./Xenium_SC/ROI_geojson/Ctrl_center/2-4-2.geojson")
Center_Ctrl_N2_T11_13_3<- geojson_sf("./Xenium_SC/ROI_geojson/Ctrl_center/2-4-3.geojson")
Center_Ctrl_N2_T11_13_4<- geojson_sf("./Xenium_SC/ROI_geojson/Ctrl_center/2-4-4.geojson")
Center_Ctrl_N2_T11_13_5<- geojson_sf("./Xenium_SC/ROI_geojson/Ctrl_center/2-4-5.geojson")
Center_Ctrl_N2_T11_13_6<- geojson_sf("./Xenium_SC/ROI_geojson/Ctrl_center/2-4-6.geojson")
Center_Ctrl_N2_T11_13_7<- geojson_sf("./Xenium_SC/ROI_geojson/Ctrl_center/2-4-7.geojson")
Center_Ctrl_N2_T11_13_8<- geojson_sf("./Xenium_SC/ROI_geojson/Ctrl_center/2-4-8.geojson")

Center_Ctrl_N2_L1_3_1<- geojson_sf("./Xenium_SC/ROI_geojson/Ctrl_center/2-5-1.geojson")
Center_Ctrl_N2_L1_3_2<- geojson_sf("./Xenium_SC/ROI_geojson/Ctrl_center/2-5-2.geojson")
Center_Ctrl_N2_L1_3_3<- geojson_sf("./Xenium_SC/ROI_geojson/Ctrl_center/2-5-3.geojson")
Center_Ctrl_N2_L1_3_4<- geojson_sf("./Xenium_SC/ROI_geojson/Ctrl_center/2-5-4.geojson")
Center_Ctrl_N2_L1_3_5<- geojson_sf("./Xenium_SC/ROI_geojson/Ctrl_center/2-5-5.geojson")
Center_Ctrl_N2_L1_3_6<- geojson_sf("./Xenium_SC/ROI_geojson/Ctrl_center/2-5-6.geojson")
Center_Ctrl_N2_L1_3_7<- geojson_sf("./Xenium_SC/ROI_geojson/Ctrl_center/2-5-7.geojson")
Center_Ctrl_N2_L1_3_8<- geojson_sf("./Xenium_SC/ROI_geojson/Ctrl_center/2-5-8.geojson")

Center_Ctrl_N2_L45_1<- geojson_sf("./Xenium_SC/ROI_geojson/Ctrl_center/2-6-1.geojson")
Center_Ctrl_N2_L45_2<- geojson_sf("./Xenium_SC/ROI_geojson/Ctrl_center/2-6-2.geojson")
Center_Ctrl_N2_L45_3<- geojson_sf("./Xenium_SC/ROI_geojson/Ctrl_center/2-6-3.geojson")
Center_Ctrl_N2_L45_4<- geojson_sf("./Xenium_SC/ROI_geojson/Ctrl_center/2-6-4.geojson")
Center_Ctrl_N2_L45_5<- geojson_sf("./Xenium_SC/ROI_geojson/Ctrl_center/2-6-5.geojson")
Center_Ctrl_N2_L45_6<- geojson_sf("./Xenium_SC/ROI_geojson/Ctrl_center/2-6-6.geojson")

Center_Ctrl_N2_L6S1_1<- geojson_sf("./Xenium_SC/ROI_geojson/Ctrl_center/2-7-1.geojson")
Center_Ctrl_N2_L6S1_2<- geojson_sf("./Xenium_SC/ROI_geojson/Ctrl_center/2-7-2.geojson")
Center_Ctrl_N2_L6S1_3<- geojson_sf("./Xenium_SC/ROI_geojson/Ctrl_center/2-7-3.geojson")
Center_Ctrl_N2_L6S1_4<- geojson_sf("./Xenium_SC/ROI_geojson/Ctrl_center/2-7-4.geojson")
Center_Ctrl_N2_L6S1_5<- geojson_sf("./Xenium_SC/ROI_geojson/Ctrl_center/2-7-5.geojson")
Center_Ctrl_N2_L6S1_6<- geojson_sf("./Xenium_SC/ROI_geojson/Ctrl_center/2-7-6.geojson")

Center_Ctrl_N2_S2_4_1<- geojson_sf("./Xenium_SC/ROI_geojson/Ctrl_center/2-8-1.geojson")
Center_Ctrl_N2_S2_4_2<- geojson_sf("./Xenium_SC/ROI_geojson/Ctrl_center/2-8-2.geojson")
Center_Ctrl_N2_S2_4_3<- geojson_sf("./Xenium_SC/ROI_geojson/Ctrl_center/2-8-3.geojson")
Center_Ctrl_N2_S2_4_4<- geojson_sf("./Xenium_SC/ROI_geojson/Ctrl_center/2-8-4.geojson")
Center_Ctrl_N2_S2_4_5<- geojson_sf("./Xenium_SC/ROI_geojson/Ctrl_center/2-8-5.geojson")

# CtrlN3
Center_Ctrl_N3_T1_4_1<- geojson_sf("./Xenium_SC/ROI_geojson/Ctrl_center/3-1-1.geojson")
Center_Ctrl_N3_T1_4_2<- geojson_sf("./Xenium_SC/ROI_geojson/Ctrl_center/3-1-2.geojson")
Center_Ctrl_N3_T1_4_3<- geojson_sf("./Xenium_SC/ROI_geojson/Ctrl_center/3-1-3.geojson")
Center_Ctrl_N3_T1_4_4<- geojson_sf("./Xenium_SC/ROI_geojson/Ctrl_center/3-1-4.geojson")
Center_Ctrl_N3_T1_4_5<- geojson_sf("./Xenium_SC/ROI_geojson/Ctrl_center/3-1-5.geojson")
Center_Ctrl_N3_T1_4_6<- geojson_sf("./Xenium_SC/ROI_geojson/Ctrl_center/3-1-6.geojson")

Center_Ctrl_N3_T5_7_1<- geojson_sf("./Xenium_SC/ROI_geojson/Ctrl_center/3-2-1.geojson")
Center_Ctrl_N3_T5_7_2<- geojson_sf("./Xenium_SC/ROI_geojson/Ctrl_center/3-2-2.geojson")
Center_Ctrl_N3_T5_7_3<- geojson_sf("./Xenium_SC/ROI_geojson/Ctrl_center/3-2-3.geojson")
Center_Ctrl_N3_T5_7_4<- geojson_sf("./Xenium_SC/ROI_geojson/Ctrl_center/3-2-4.geojson")
Center_Ctrl_N3_T5_7_5<- geojson_sf("./Xenium_SC/ROI_geojson/Ctrl_center/3-2-5.geojson")
Center_Ctrl_N3_T5_7_6<- geojson_sf("./Xenium_SC/ROI_geojson/Ctrl_center/3-2-6.geojson")

Center_Ctrl_N3_T8_10_1<- geojson_sf("./Xenium_SC/ROI_geojson/Ctrl_center/3-3-1.geojson")
Center_Ctrl_N3_T8_10_2<- geojson_sf("./Xenium_SC/ROI_geojson/Ctrl_center/3-3-2.geojson")
Center_Ctrl_N3_T8_10_3<- geojson_sf("./Xenium_SC/ROI_geojson/Ctrl_center/3-3-3.geojson")
Center_Ctrl_N3_T8_10_4<- geojson_sf("./Xenium_SC/ROI_geojson/Ctrl_center/3-3-4.geojson")
Center_Ctrl_N3_T8_10_5<- geojson_sf("./Xenium_SC/ROI_geojson/Ctrl_center/3-3-5.geojson")
Center_Ctrl_N3_T8_10_6<- geojson_sf("./Xenium_SC/ROI_geojson/Ctrl_center/3-3-6.geojson")

Center_Ctrl_N3_T11_13_1<- geojson_sf("./Xenium_SC/ROI_geojson/Ctrl_center/3-4-1.geojson")
Center_Ctrl_N3_T11_13_2<- geojson_sf("./Xenium_SC/ROI_geojson/Ctrl_center/3-4-2.geojson")
Center_Ctrl_N3_T11_13_3<- geojson_sf("./Xenium_SC/ROI_geojson/Ctrl_center/3-4-3.geojson")
Center_Ctrl_N3_T11_13_4<- geojson_sf("./Xenium_SC/ROI_geojson/Ctrl_center/3-4-4.geojson")
Center_Ctrl_N3_T11_13_5<- geojson_sf("./Xenium_SC/ROI_geojson/Ctrl_center/3-4-5.geojson")
Center_Ctrl_N3_T11_13_6<- geojson_sf("./Xenium_SC/ROI_geojson/Ctrl_center/3-4-6.geojson")
Center_Ctrl_N3_T11_13_7<- geojson_sf("./Xenium_SC/ROI_geojson/Ctrl_center/3-4-7.geojson")

Center_Ctrl_N3_L1_3_1<- geojson_sf("./Xenium_SC/ROI_geojson/Ctrl_center/3-5-1.geojson")
Center_Ctrl_N3_L1_3_2<- geojson_sf("./Xenium_SC/ROI_geojson/Ctrl_center/3-5-2.geojson")
Center_Ctrl_N3_L1_3_3<- geojson_sf("./Xenium_SC/ROI_geojson/Ctrl_center/3-5-3.geojson")
Center_Ctrl_N3_L1_3_4<- geojson_sf("./Xenium_SC/ROI_geojson/Ctrl_center/3-5-4.geojson")
Center_Ctrl_N3_L1_3_5<- geojson_sf("./Xenium_SC/ROI_geojson/Ctrl_center/3-5-5.geojson")
Center_Ctrl_N3_L1_3_6<- geojson_sf("./Xenium_SC/ROI_geojson/Ctrl_center/3-5-6.geojson")
Center_Ctrl_N3_L1_3_7<- geojson_sf("./Xenium_SC/ROI_geojson/Ctrl_center/3-5-7.geojson")
Center_Ctrl_N3_L1_3_8<- geojson_sf("./Xenium_SC/ROI_geojson/Ctrl_center/3-5-8.geojson")

Center_Ctrl_N3_L1_3_9<- geojson_sf("./Xenium_SC/ROI_geojson/Ctrl_center/3-6-1.geojson")
Center_Ctrl_N3_L1_3_10<- geojson_sf("./Xenium_SC/ROI_geojson/Ctrl_center/3-6-2.geojson")
Center_Ctrl_N3_L1_3_11<- geojson_sf("./Xenium_SC/ROI_geojson/Ctrl_center/3-6-3.geojson")
Center_Ctrl_N3_L1_3_12<- geojson_sf("./Xenium_SC/ROI_geojson/Ctrl_center/3-6-4.geojson")
Center_Ctrl_N3_L1_3_13<- geojson_sf("./Xenium_SC/ROI_geojson/Ctrl_center/3-6-5.geojson")
Center_Ctrl_N3_L1_3_14<- geojson_sf("./Xenium_SC/ROI_geojson/Ctrl_center/3-6-6.geojson")
Center_Ctrl_N3_L1_3_15<- geojson_sf("./Xenium_SC/ROI_geojson/Ctrl_center/3-6-7.geojson")
Center_Ctrl_N3_L1_3_16<- geojson_sf("./Xenium_SC/ROI_geojson/Ctrl_center/3-6-8.geojson")

Center_Ctrl_N3_L45_1<- geojson_sf("./Xenium_SC/ROI_geojson/Ctrl_center/3-7-1.geojson")
Center_Ctrl_N3_L45_2<- geojson_sf("./Xenium_SC/ROI_geojson/Ctrl_center/3-7-2.geojson")
Center_Ctrl_N3_L45_3<- geojson_sf("./Xenium_SC/ROI_geojson/Ctrl_center/3-7-3.geojson")
Center_Ctrl_N3_L45_4<- geojson_sf("./Xenium_SC/ROI_geojson/Ctrl_center/3-7-4.geojson")
Center_Ctrl_N3_L45_5<- geojson_sf("./Xenium_SC/ROI_geojson/Ctrl_center/3-7-5.geojson")
Center_Ctrl_N3_L45_6<- geojson_sf("./Xenium_SC/ROI_geojson/Ctrl_center/3-7-6.geojson")

Center_Ctrl_N3_L6S1_1<- geojson_sf("./Xenium_SC/ROI_geojson/Ctrl_center/3-8-1.geojson")
Center_Ctrl_N3_L6S1_2<- geojson_sf("./Xenium_SC/ROI_geojson/Ctrl_center/3-8-2.geojson")
Center_Ctrl_N3_L6S1_3<- geojson_sf("./Xenium_SC/ROI_geojson/Ctrl_center/3-8-3.geojson")
Center_Ctrl_N3_L6S1_4<- geojson_sf("./Xenium_SC/ROI_geojson/Ctrl_center/3-8-4.geojson")
Center_Ctrl_N3_L6S1_5<- geojson_sf("./Xenium_SC/ROI_geojson/Ctrl_center/3-8-5.geojson")
Center_Ctrl_N3_L6S1_6<- geojson_sf("./Xenium_SC/ROI_geojson/Ctrl_center/3-8-6.geojson")

# ColdN1
Center_Cold_N1_T1_4_1<- geojson_sf("./Xenium_SC/ROI_geojson/Cold_center/1-1-1.geojson")
Center_Cold_N1_T1_4_2<- geojson_sf("./Xenium_SC/ROI_geojson/Cold_center/1-1-2.geojson")
Center_Cold_N1_T1_4_3<- geojson_sf("./Xenium_SC/ROI_geojson/Cold_center/1-1-3.geojson")
Center_Cold_N1_T1_4_4<- geojson_sf("./Xenium_SC/ROI_geojson/Cold_center/1-1-4.geojson")
Center_Cold_N1_T1_4_5<- geojson_sf("./Xenium_SC/ROI_geojson/Cold_center/1-1-5.geojson")
Center_Cold_N1_T1_4_6<- geojson_sf("./Xenium_SC/ROI_geojson/Cold_center/1-1-6.geojson")

Center_Cold_N1_T5_7_1<- geojson_sf("./Xenium_SC/ROI_geojson/Cold_center/1-2-1.geojson")
Center_Cold_N1_T5_7_2<- geojson_sf("./Xenium_SC/ROI_geojson/Cold_center/1-2-2.geojson")
Center_Cold_N1_T5_7_3<- geojson_sf("./Xenium_SC/ROI_geojson/Cold_center/1-2-3.geojson")
Center_Cold_N1_T5_7_4<- geojson_sf("./Xenium_SC/ROI_geojson/Cold_center/1-2-4.geojson")
Center_Cold_N1_T5_7_5<- geojson_sf("./Xenium_SC/ROI_geojson/Cold_center/1-2-5.geojson")
Center_Cold_N1_T5_7_6<- geojson_sf("./Xenium_SC/ROI_geojson/Cold_center/1-2-6.geojson")

Center_Cold_N1_T8_10_1<- geojson_sf("./Xenium_SC/ROI_geojson/Cold_center/1-3-1.geojson")
Center_Cold_N1_T8_10_2<- geojson_sf("./Xenium_SC/ROI_geojson/Cold_center/1-3-2.geojson")
Center_Cold_N1_T8_10_3<- geojson_sf("./Xenium_SC/ROI_geojson/Cold_center/1-3-3.geojson")
Center_Cold_N1_T8_10_4<- geojson_sf("./Xenium_SC/ROI_geojson/Cold_center/1-3-4.geojson")
Center_Cold_N1_T8_10_5<- geojson_sf("./Xenium_SC/ROI_geojson/Cold_center/1-3-5.geojson")
Center_Cold_N1_T8_10_6<- geojson_sf("./Xenium_SC/ROI_geojson/Cold_center/1-3-6.geojson")

Center_Cold_N1_T11_13_1<- geojson_sf("./Xenium_SC/ROI_geojson/Cold_center/1-4-1.geojson")
Center_Cold_N1_T11_13_2<- geojson_sf("./Xenium_SC/ROI_geojson/Cold_center/1-4-2.geojson")
Center_Cold_N1_T11_13_3<- geojson_sf("./Xenium_SC/ROI_geojson/Cold_center/1-4-3.geojson")
Center_Cold_N1_T11_13_4<- geojson_sf("./Xenium_SC/ROI_geojson/Cold_center/1-4-4.geojson")
Center_Cold_N1_T11_13_5<- geojson_sf("./Xenium_SC/ROI_geojson/Cold_center/1-4-5.geojson")
Center_Cold_N1_T11_13_6<- geojson_sf("./Xenium_SC/ROI_geojson/Cold_center/1-4-6.geojson")
Center_Cold_N1_T11_13_7<- geojson_sf("./Xenium_SC/ROI_geojson/Cold_center/1-4-7.geojson")
Center_Cold_N1_T11_13_8<- geojson_sf("./Xenium_SC/ROI_geojson/Cold_center/1-4-8.geojson")

Center_Cold_N1_L1_3_1<- geojson_sf("./Xenium_SC/ROI_geojson/Cold_center/1-5-1.geojson")
Center_Cold_N1_L1_3_2<- geojson_sf("./Xenium_SC/ROI_geojson/Cold_center/1-5-2.geojson")
Center_Cold_N1_L1_3_3<- geojson_sf("./Xenium_SC/ROI_geojson/Cold_center/1-5-3.geojson")
Center_Cold_N1_L1_3_4<- geojson_sf("./Xenium_SC/ROI_geojson/Cold_center/1-5-4.geojson")
Center_Cold_N1_L1_3_5<- geojson_sf("./Xenium_SC/ROI_geojson/Cold_center/1-5-5.geojson")
Center_Cold_N1_L1_3_6<- geojson_sf("./Xenium_SC/ROI_geojson/Cold_center/1-5-6.geojson")

Center_Cold_N1_L45_1<- geojson_sf("./Xenium_SC/ROI_geojson/Cold_center/1-6-1.geojson")
Center_Cold_N1_L45_2<- geojson_sf("./Xenium_SC/ROI_geojson/Cold_center/1-6-2.geojson")
Center_Cold_N1_L45_3<- geojson_sf("./Xenium_SC/ROI_geojson/Cold_center/1-6-3.geojson")
Center_Cold_N1_L45_4<- geojson_sf("./Xenium_SC/ROI_geojson/Cold_center/1-6-4.geojson")
Center_Cold_N1_L45_5<- geojson_sf("./Xenium_SC/ROI_geojson/Cold_center/1-6-5.geojson")
Center_Cold_N1_L45_6<- geojson_sf("./Xenium_SC/ROI_geojson/Cold_center/1-6-6.geojson")

Center_Cold_N1_L6S1_1<- geojson_sf("./Xenium_SC/ROI_geojson/Cold_center/1-7-1.geojson")
Center_Cold_N1_L6S1_2<- geojson_sf("./Xenium_SC/ROI_geojson/Cold_center/1-7-2.geojson")
Center_Cold_N1_L6S1_3<- geojson_sf("./Xenium_SC/ROI_geojson/Cold_center/1-7-3.geojson")
Center_Cold_N1_L6S1_4<- geojson_sf("./Xenium_SC/ROI_geojson/Cold_center/1-7-4.geojson")
Center_Cold_N1_L6S1_5<- geojson_sf("./Xenium_SC/ROI_geojson/Cold_center/1-7-5.geojson")
Center_Cold_N1_L6S1_6<- geojson_sf("./Xenium_SC/ROI_geojson/Cold_center/1-7-6.geojson")

Center_Cold_N1_S2_4_1<- geojson_sf("./Xenium_SC/ROI_geojson/Cold_center/1-8-1.geojson")
Center_Cold_N1_S2_4_2<- geojson_sf("./Xenium_SC/ROI_geojson/Cold_center/1-8-2.geojson")
Center_Cold_N1_S2_4_3<- geojson_sf("./Xenium_SC/ROI_geojson/Cold_center/1-8-3.geojson")
Center_Cold_N1_S2_4_4<- geojson_sf("./Xenium_SC/ROI_geojson/Cold_center/1-8-4.geojson")
Center_Cold_N1_S2_4_5<- geojson_sf("./Xenium_SC/ROI_geojson/Cold_center/1-8-5.geojson")
Center_Cold_N1_S2_4_6<- geojson_sf("./Xenium_SC/ROI_geojson/Cold_center/1-8-6.geojson")
Center_Cold_N1_S2_4_7<- geojson_sf("./Xenium_SC/ROI_geojson/Cold_center/1-8-7.geojson")

# ColdN2
Center_Cold_N2_T1_4_1<- geojson_sf("./Xenium_SC/ROI_geojson/Cold_center/2-1-1.geojson")
Center_Cold_N2_T1_4_2<- geojson_sf("./Xenium_SC/ROI_geojson/Cold_center/2-1-2.geojson")
Center_Cold_N2_T1_4_3<- geojson_sf("./Xenium_SC/ROI_geojson/Cold_center/2-1-3.geojson")
Center_Cold_N2_T1_4_4<- geojson_sf("./Xenium_SC/ROI_geojson/Cold_center/2-1-4.geojson")
Center_Cold_N2_T1_4_5<- geojson_sf("./Xenium_SC/ROI_geojson/Cold_center/2-1-5.geojson")
Center_Cold_N2_T1_4_6<- geojson_sf("./Xenium_SC/ROI_geojson/Cold_center/2-1-6.geojson")
# 
# Center_Cold_N2_T5_7_1<- geojson_sf("./Xenium_SC/ROI_geojson/Cold_center/2-2-1.geojson")
# Center_Cold_N2_T5_7_2<- geojson_sf("./Xenium_SC/ROI_geojson/Cold_center/2-2-2.geojson")
# Center_Cold_N2_T5_7_3<- geojson_sf("./Xenium_SC/ROI_geojson/Cold_center/2-2-3.geojson")
# Center_Cold_N2_T5_7_4<- geojson_sf("./Xenium_SC/ROI_geojson/Cold_center/2-2-4.geojson")
# Center_Cold_N2_T5_7_5<- geojson_sf("./Xenium_SC/ROI_geojson/Cold_center/2-2-5.geojson")
# Center_Cold_N2_T5_7_6<- geojson_sf("./Xenium_SC/ROI_geojson/Cold_center/2-2-6.geojson")
# Center_Cold_N2_T5_7_7<- geojson_sf("./Xenium_SC/ROI_geojson/Cold_center/2-2-7.geojson")
# Center_Cold_N2_T5_7_8<- geojson_sf("./Xenium_SC/ROI_geojson/Cold_center/2-2-8.geojson")

Center_Cold_N2_T8_10_1<- geojson_sf("./Xenium_SC/ROI_geojson/Cold_center/2-3-1.geojson")
Center_Cold_N2_T8_10_2<- geojson_sf("./Xenium_SC/ROI_geojson/Cold_center/2-3-2.geojson")
Center_Cold_N2_T8_10_3<- geojson_sf("./Xenium_SC/ROI_geojson/Cold_center/2-3-3.geojson")
Center_Cold_N2_T8_10_4<- geojson_sf("./Xenium_SC/ROI_geojson/Cold_center/2-3-4.geojson")
Center_Cold_N2_T8_10_5<- geojson_sf("./Xenium_SC/ROI_geojson/Cold_center/2-3-5.geojson")
Center_Cold_N2_T8_10_6<- geojson_sf("./Xenium_SC/ROI_geojson/Cold_center/2-3-6.geojson")

Center_Cold_N2_T11_13_1<- geojson_sf("./Xenium_SC/ROI_geojson/Cold_center/2-4-1.geojson")
Center_Cold_N2_T11_13_2<- geojson_sf("./Xenium_SC/ROI_geojson/Cold_center/2-4-2.geojson")
Center_Cold_N2_T11_13_3<- geojson_sf("./Xenium_SC/ROI_geojson/Cold_center/2-4-3.geojson")
Center_Cold_N2_T11_13_4<- geojson_sf("./Xenium_SC/ROI_geojson/Cold_center/2-4-4.geojson")
Center_Cold_N2_T11_13_5<- geojson_sf("./Xenium_SC/ROI_geojson/Cold_center/2-4-5.geojson")
Center_Cold_N2_T11_13_6<- geojson_sf("./Xenium_SC/ROI_geojson/Cold_center/2-4-6.geojson")
Center_Cold_N2_T11_13_7<- geojson_sf("./Xenium_SC/ROI_geojson/Cold_center/2-4-7.geojson")
Center_Cold_N2_T11_13_8<- geojson_sf("./Xenium_SC/ROI_geojson/Cold_center/2-4-8.geojson")

Center_Cold_N2_L1_3_1<- geojson_sf("./Xenium_SC/ROI_geojson/Cold_center/2-5-1.geojson")
Center_Cold_N2_L1_3_2<- geojson_sf("./Xenium_SC/ROI_geojson/Cold_center/2-5-2.geojson")
Center_Cold_N2_L1_3_3<- geojson_sf("./Xenium_SC/ROI_geojson/Cold_center/2-5-3.geojson")
Center_Cold_N2_L1_3_4<- geojson_sf("./Xenium_SC/ROI_geojson/Cold_center/2-5-4.geojson")
Center_Cold_N2_L1_3_5<- geojson_sf("./Xenium_SC/ROI_geojson/Cold_center/2-5-5.geojson")
Center_Cold_N2_L1_3_6<- geojson_sf("./Xenium_SC/ROI_geojson/Cold_center/2-5-6.geojson")

Center_Cold_N2_L45_1<- geojson_sf("./Xenium_SC/ROI_geojson/Cold_center/2-6-1.geojson")
Center_Cold_N2_L45_2<- geojson_sf("./Xenium_SC/ROI_geojson/Cold_center/2-6-2.geojson")
Center_Cold_N2_L45_3<- geojson_sf("./Xenium_SC/ROI_geojson/Cold_center/2-6-3.geojson")
Center_Cold_N2_L45_4<- geojson_sf("./Xenium_SC/ROI_geojson/Cold_center/2-6-4.geojson")
Center_Cold_N2_L45_5<- geojson_sf("./Xenium_SC/ROI_geojson/Cold_center/2-6-5.geojson")
Center_Cold_N2_L45_6<- geojson_sf("./Xenium_SC/ROI_geojson/Cold_center/2-6-6.geojson")

Center_Cold_N2_L6S1_1<- geojson_sf("./Xenium_SC/ROI_geojson/Cold_center/2-7-1.geojson")
Center_Cold_N2_L6S1_2<- geojson_sf("./Xenium_SC/ROI_geojson/Cold_center/2-7-2.geojson")
Center_Cold_N2_L6S1_3<- geojson_sf("./Xenium_SC/ROI_geojson/Cold_center/2-7-3.geojson")
Center_Cold_N2_L6S1_4<- geojson_sf("./Xenium_SC/ROI_geojson/Cold_center/2-7-4.geojson")
Center_Cold_N2_L6S1_5<- geojson_sf("./Xenium_SC/ROI_geojson/Cold_center/2-7-5.geojson")
Center_Cold_N2_L6S1_6<- geojson_sf("./Xenium_SC/ROI_geojson/Cold_center/2-7-6.geojson")


Center_Cold_N2_S2_4_1<- geojson_sf("./Xenium_SC/ROI_geojson/Cold_center/2-8-1.geojson")
Center_Cold_N2_S2_4_2<- geojson_sf("./Xenium_SC/ROI_geojson/Cold_center/2-8-2.geojson")
Center_Cold_N2_S2_4_3<- geojson_sf("./Xenium_SC/ROI_geojson/Cold_center/2-8-3.geojson")
Center_Cold_N2_S2_4_4<- geojson_sf("./Xenium_SC/ROI_geojson/Cold_center/2-8-4.geojson")
Center_Cold_N2_S2_4_5<- geojson_sf("./Xenium_SC/ROI_geojson/Cold_center/2-8-5.geojson")
Center_Cold_N2_S2_4_6<- geojson_sf("./Xenium_SC/ROI_geojson/Cold_center/2-8-6.geojson")
Center_Cold_N2_S2_4_7<- geojson_sf("./Xenium_SC/ROI_geojson/Cold_center/2-8-7.geojson")


# ColdN3
Center_Cold_N3_T1_4_1<- geojson_sf("./Xenium_SC/ROI_geojson/Cold_center/3-1-1.geojson")
Center_Cold_N3_T1_4_2<- geojson_sf("./Xenium_SC/ROI_geojson/Cold_center/3-1-2.geojson")
Center_Cold_N3_T1_4_3<- geojson_sf("./Xenium_SC/ROI_geojson/Cold_center/3-1-3.geojson")

Center_Cold_N3_T5_7_1<- geojson_sf("./Xenium_SC/ROI_geojson/Cold_center/3-2-1.geojson")
Center_Cold_N3_T5_7_2<- geojson_sf("./Xenium_SC/ROI_geojson/Cold_center/3-2-2.geojson")
Center_Cold_N3_T5_7_3<- geojson_sf("./Xenium_SC/ROI_geojson/Cold_center/3-2-3.geojson")
Center_Cold_N3_T5_7_4<- geojson_sf("./Xenium_SC/ROI_geojson/Cold_center/3-2-4.geojson")
Center_Cold_N3_T5_7_5<- geojson_sf("./Xenium_SC/ROI_geojson/Cold_center/3-2-5.geojson")
Center_Cold_N3_T5_7_6<- geojson_sf("./Xenium_SC/ROI_geojson/Cold_center/3-2-6.geojson")

Center_Cold_N3_T8_10_1<- geojson_sf("./Xenium_SC/ROI_geojson/Cold_center/3-3-1.geojson")
Center_Cold_N3_T8_10_2<- geojson_sf("./Xenium_SC/ROI_geojson/Cold_center/3-3-2.geojson")
Center_Cold_N3_T8_10_3<- geojson_sf("./Xenium_SC/ROI_geojson/Cold_center/3-3-3.geojson")

Center_Cold_N3_T11_13_1<- geojson_sf("./Xenium_SC/ROI_geojson/Cold_center/3-4-1.geojson")
Center_Cold_N3_T11_13_2<- geojson_sf("./Xenium_SC/ROI_geojson/Cold_center/3-4-2.geojson")
Center_Cold_N3_T11_13_3<- geojson_sf("./Xenium_SC/ROI_geojson/Cold_center/3-4-3.geojson")

Center_Cold_N3_L1_3_1<- geojson_sf("./Xenium_SC/ROI_geojson/Cold_center/3-5-1.geojson")
Center_Cold_N3_L1_3_2<- geojson_sf("./Xenium_SC/ROI_geojson/Cold_center/3-5-2.geojson")
Center_Cold_N3_L1_3_3<- geojson_sf("./Xenium_SC/ROI_geojson/Cold_center/3-5-3.geojson")

Center_Cold_N3_L45_1<- geojson_sf("./Xenium_SC/ROI_geojson/Cold_center/3-6-1.geojson")
Center_Cold_N3_L45_2<- geojson_sf("./Xenium_SC/ROI_geojson/Cold_center/3-6-2.geojson")
Center_Cold_N3_L45_3<- geojson_sf("./Xenium_SC/ROI_geojson/Cold_center/3-6-3.geojson")
Center_Cold_N3_L45_4<- geojson_sf("./Xenium_SC/ROI_geojson/Cold_center/3-6-4.geojson")
Center_Cold_N3_L45_5<- geojson_sf("./Xenium_SC/ROI_geojson/Cold_center/3-6-5.geojson")

Center_Cold_N3_L6S1_1<- geojson_sf("./Xenium_SC/ROI_geojson/Cold_center/3-7-1.geojson")
Center_Cold_N3_L6S1_2<- geojson_sf("./Xenium_SC/ROI_geojson/Cold_center/3-7-2.geojson")
Center_Cold_N3_L6S1_3<- geojson_sf("./Xenium_SC/ROI_geojson/Cold_center/3-7-3.geojson")

Center_Cold_N3_S2_4_1<- geojson_sf("./Xenium_SC/ROI_geojson/Cold_center/3-8-1.geojson")
Center_Cold_N3_S2_4_2<- geojson_sf("./Xenium_SC/ROI_geojson/Cold_center/3-8-2.geojson")
Center_Cold_N3_S2_4_3<- geojson_sf("./Xenium_SC/ROI_geojson/Cold_center/3-8-3.geojson")
